- 
  name: check connectivity to target server
  hosts: all
  tasks:
    - name: test shell output
      shell:
#        echo "\n Present working directory is" `pwd` 
        ls -al && echo -e "\n ciao" 
      args:
        #chdir: "/apps/tomcat/"
      register: out
    
    - debug: var=out.stdout_lines
